### ISSUE TITLE
(BUG) Breaking menus

### ISSUE THREAD

**Issue by nvb-uy** [Benjamin-Norton/AllTheTrims#1]
The mod seems to be conflicting with both FancyMenu and Mod Menu. It also disables all active resource packs.

## **Issues:**
- Completely moves the buttons in the main menu (FancyMenu)
- Makes the mods button use its translation key instead (Mod Menu)
- Disables all resource packs

## How it looks before installing the mod:

![Before Installation](https://cdn.discordapp.com/attachments/1073529888507691008/1120130649714610296/image.png)

## How it looks after installing the mod:

![After Installation](https://cdn.discordapp.com/attachments/1073529888507691008/1120129494053830676/image.png)

**Comment by nvb-uy** [comment]
Keep in mind that the issues disappear after removing the mod

**Comment by Bawnorton** [comment]
Well that’s an odd one as this mod doesn’t interact with menus at all. Can you send me your latest.log so I can fix this.

**Comment by Bawnorton** [comment]
In a vacuum, this mod doesn't break mod menu or fancy menus or disable any resource packs so I guess this mod breaks something earlier that prevents those from loading properly. I will need a mod list or a log tho. I assume you are loading a lot of mods here so it could be that it is registering too many custom models for mc to handle.

**Comment by Bawnorton** [comment]
I think I have found and fixed the issue in 1.0.2, the better end mod does not use typical armour models and thus breaks the mod and all resource packs as it cannot find the model jsons. 
Will leave this open for confirmation that that was the issue.

**Comment by Bawnorton** [comment]
Since 1.3.0 All The Trims no longer generates unique model files for each trim material and is now fully dynamic.
