### ISSUE TITLE
[Bug Report] Repeating crash on launch

### ISSUE THREAD

**Issue by EarlyWizard** [Benjamin-Norton/AllTheTrims#10]
Game crashes on launch, repetitive crash
"The game crashed whilst rendering overlay
Error: java.lang.NoClassDefFoundError: Could not initialize class com.bawnorton.allthetrims.util.DebugHelper"
Using version 3.1.3 for Forge (allthetrims-3.1.3-forge+1.20.1.jar)

![image](https://github.com/Benjamin-Norton/AllTheTrims/assets/83371343/e6c6512b-200b-4385-b003-9befacc672d4)

Latest log and crash log: 
[latest.log](https://github.com/Benjamin-Norton/AllTheTrims/files/12223030/latest.log)
[crash-2023-07-31_16.51.57-client.txt](https://github.com/Benjamin-Norton/AllTheTrims/files/12223032/crash-2023-07-31_16.51.57-client.txt)

Edit: This is with ONLY the All The Trims mod, no other mods are loaded

**Comment by Bawnorton** [comment]
Well this makes no sense lol, I'll look into this tomorrow. This type of crash should not even be possible.

**Comment by Bawnorton** [comment]
Can you try deleting and reinstalling the mod.

**Comment by EarlyWizard** [comment]
> Can you try deleting and reinstalling the mod.

Tried, instead of a repeating crash I got all my text replaced with squares. (Commented about this on the mod on CurseForge)
Forge version is 1.20.1-forge-47.1.0 by the way.

**Comment by Bawnorton** [comment]
Can you send the log for when that happens, thanks.

**Comment by EarlyWizard** [comment]
> Can you send the log for when that happens, thanks.

Tried starting Minecraft again, started getting the crash again. I reinstalled the mod, but I didn't get the "text with squares" bug ever. I'll try and replicate the text bug again and I'll send the log for when it happens ASAP. (If there's a way to get old logs then tell me please)
EDIT: I can't seem to replicate the text bug by any means. I tried starting the mod on the most recent Forge version, I tried starting the mod on an older Forge version and THEN a new Forge version, but nothing seems to work. I'll force it by loading Optifine, but I'm not sure if that will work (EDIT 2: loading the mod with other mods and optifine did not work)
(Yes, you have my permission to call me stupid for forgetting to get the latest.log before starting Minecraft again.)
