### ISSUE TITLE
game crash on launch

### ISSUE THREAD

**Issue by ptrnd** [Benjamin-Norton/AllTheTrims#15]
**Expected Behavior**
the game starts properly.

**Actual Behavior**
the game crash on launch.

**What version of the mod are you using**
All The Trims 3.2.5
Fabric 1.20.1

**Helpful Files**
[2023-09-27-6.log](https://github.com/Bawnorton/AllTheTrims/files/12740946/2023-09-27-6.log)

**Comment by Bawnorton** [comment]
Please don't report unrelated bugs on my issue tracker.

Your issue is that you need to update MemoryLeakFix.

**Comment by ptrnd** [comment]
I really can't read the error. All of that mods working well until I put "All The Trims" mod a few hours ago. I want to ask people on a discord server that using same mod but still no result, so I drop this here. Thank you very much.

**Comment by Bawnorton** [comment]
Ok fair enough, can't blame you for this one. MemoryLeakFix used to do something that it wasn't supposed to which can cause it to implode when introduced to newer versions of a library that a lot of mods use, including mine.
