### ISSUE TITLE
[Suggestion] Remove all unwanted items from 'minecraft:trim_materials'

### ISSUE THREAD

**Issue by lxly9** [Benjamin-Norton/AllTheTrims#16]
It would be great if the mod dynamically removes the entries from the 'minecraft:trim_materials' tag so that there is no recipe clutter and in turn only parse the 'allthetrims:whitelist' tag into the 'minecraft:trim_materials' tag as to avoid showing the unwanted materials. 
It would also be quite cool to be able to configure which armor can have a trim applied and which doesnt, as all vaguely armor related items can currently be trimmed.

**Comment by Bawnorton** [comment]
Whitelisting is being removed, see [this comment](https://github.com/Bawnorton/AllTheTrims/issues/14#issuecomment-1751497542), but I am working on simplifying the recipes

**Comment by Bawnorton** [comment]
Recipe viewing improved in 3.3.0
