### ISSUE TITLE
[Bug Report] Unexpected crash when creating a world

### ISSUE THREAD

**Issue by Colaskink** [Benjamin-Norton/AllTheTrims#19]
I'm using a quite large modpack so I'm unsure which mod could be causing the incompatibility, hoping it can be traced through the logs.

**Expected Behaviour**
Being able to create a world

**Actual Behaviour**
Upon pressing create new world, game crashes after a few seconds

**Steps to Reproduce**
Press "singleplayer"
Press "create new world"

**What version of the mod are you using**
3.3.4

**Helpful Files**
Crash log:
[crash-2023-11-14_17.52.10-client.txt](https://github.com/Bawnorton/AllTheTrims/files/13352058/crash-2023-11-14_17.52.10-client.txt)

Latest.log:
[latest.log](https://github.com/Bawnorton/AllTheTrims/files/13352064/latest.log)

**Comment by Bawnorton** [comment]
I'll look into this, unfortunately the cause isn't clear so this may take a bit.

**Comment by syncratio** [comment]
Downgrading to ~~3.2.5~~ **3.3.2** fixes the issue, if that helps.
