### ISSUE TITLE
[Bug Report] Trims aren't working on Crystalite armor

### ISSUE THREAD

**Issue by Cristelknight** [Benjamin-Norton/AllTheTrims#2]
**Expected Behaviour**
Render armor trim on Crystalite armor (from Better End)

**Actual Behaviour**
Armor trims don't show up

**Steps to Reproduce**
- Install Better End
- Try to trim a crystalite armor piece

**What version of the mod are you using**
- All The Trims 2.0.0
- Better End 4.0.6

**Comment by Bawnorton** [comment]
Better end armour uses a completely custom armour model system, I do have support for the mod planned but it will require a lot of work as the process of adding trims to their armour would require its own dedicated system.

**Comment by Cristelknight** [comment]
Oh. All other armors of better end worked. So I didn't expect the Crystalite one to have an special Renderer

**Comment by Bawnorton** [comment]
The item models for the other amour is broken but yeah the crystalite armour model itself is broken.

**Comment by Cristelknight** [comment]
Will you fix this in the near future? If not, no problem. I don't **need** to trim my armor. But would be cool

**Comment by Bawnorton** [comment]
Not sure, I gave it a try yesterday and the trim rendering part does not work as the the uv is completely wrong, meaning a fix is going to take a lot more work unfortunately.

**Comment by Bawnorton** [comment]
Follow along here for any more developments. https://github.com/quiqueck/BCLib/issues/107
