### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by xanthian** [Benjamin-Norton/AllTheTrims#20]
Not sure this is necessary? 😛
v3.3.4 fabric 1.20.1
  ![image](https://github.com/Bawnorton/AllTheTrims/assets/7688001/019e69d5-38e1-4214-8c14-fbc644862607)

**Comment by Bawnorton** [comment]
Eh probably, it's normally only a few lines, even in big packs because there aren't many equipment items that don't use the armour slots. Of course, a dedicated shield mod is gonna cause the logs to spam a bit.
