### ISSUE TITLE
[Suggestion] Trim Materials & Armor Blacklist?

### ISSUE THREAD

**Issue by MysticcWaters** [Benjamin-Norton/AllTheTrims#22]
Possibly add a tag blacklist for items that can be considered for trims, as well as armor that can be trimmed? I know that this mod isn't compatible with modded armor that uses it's own rendering system (an example being Iron's Soells & Spellbooks robes), but it still allows for those armor pieces to be trimmed despite that. Would be nice to have a blacklist for modpack making.

If this isn't in the plans I would understand, but I find it to be a pretty big thing.

**Comment by Bawnorton** [comment]
See #27, it is planned.. at some point
