### ISSUE TITLE
[Bug Report] Crash at Launch Caused by Incompatibility

### ISSUE THREAD

**Issue by ghost** [Benjamin-Norton/AllTheTrims#23]
**Expected Behaviour**
Normal game launch

**Actual Behaviour**
Crash with All The Trims and another Unknown Mod in the list.

**Steps to Reproduce**
Launch game

**What version of the mod are you using**
allthetrims-3.3.7-forge+1.20.1.jar

**Helpful Files**
https://paste.ee/p/Z6OTX

**Comment by Bawnorton** [comment]
Something is removing the trim entries from builtin armour models, allthetrims cannot function without being able to read what vanilla uses, whichever mod is doing this (likely an armour model changing mod or texture pack) is incompatible with allthetrims

**Comment by ghost** [comment]
Can you tell which mod is causing this crash? I'm having trouble finding it without doing the binary method.

**Comment by Bawnorton** [comment]
no idea
