### ISSUE TITLE
[Bug Report] Incompatibility with Elytra Trims

### ISSUE THREAD

**Issue by obsidian29** [Benjamin-Norton/AllTheTrims#24]
**Expected Behaviour**
Honestly, I didn't expect compatibility to already be coded in, but _were_ there compatibility, I'd expect the trims added by this mod to work just fine with trimmed elytra.

**Actual Behaviour**
No trim appeared on elytra while wearing it, and missingno.png covering elytra in smithing table GUI.

**Steps to Reproduce**
- Install both All The Trims and Elytra Trims at the same time.
- Apply a trim from All The Trims to the elytra.
- Observe in the smithing table GUI the very nice missingno.png.
- Wear the elytra. Observe the complete lack of trim.

**What version of the mod are you using**
3.4.2 for Fabric 1.20.1

**Helpful Files**
[latest.log](https://github.com/Bawnorton/AllTheTrims/files/14543949/latest.log)
![image](https://github.com/Bawnorton/AllTheTrims/assets/29574479/734707f2-5c1b-4ba0-88a2-c92b761126f6)

I recognize that this isn't strictly a _bug_, but I got this mod specifically to have echo shard trim on my elytra to match the echo armor I added in my own mod. I really hope you decide to add it. Either way, thank you for the mod.

**Comment by Rymka69** [comment]
I am pretty sure at one point this mod worked with elytra trims, now I came here to post the same issue, but found one already existing.

**Comment by Bawnorton** [comment]
Fixed in 4.x
