### ISSUE TITLE
[Feature Request] Detecting if the armor is the same as the trim

### ISSUE THREAD

**Issue by obsidian29** [Benjamin-Norton/AllTheTrims#25]
In the event of modded items, I was hoping the mod would detect, maybe based on the ID or the language string, if a modded armor was the same material as an existing or All The Trims-added trim material. It doesn't seem to be the case - my mod's Ender Quartz armor does not look good with Ender Quartz trim, it just blends in.

I would like to request, if it is possible, for this feature to be added - though I can't really think of how one could do it reliably, given linguistic barriers and differing conventions, without perhaps a .json or other config defining which armor should use _darker for which trim. Perhaps modders could include support hooks to autogenerate this .json as well rather than requiring the user to always do it.

**Comment by Bawnorton** [comment]
Sorry, not really feasible
