### ISSUE TITLE
[Bug Report] Material text display error on forge server

### ISSUE THREAD

**Issue by anzai249** [Benjamin-Norton/AllTheTrims#26]
**Expected Behaviour**
The upgraded armour should display the trim material.

**Actual Behaviour**
![image](https://github.com/Bawnorton/AllTheTrims/assets/32564494/3a54bb3e-9110-4ec6-aa49-abc5bab66031)

**%s Material**. It only happens in multiplayer, the material I used on this image is crabbersdelight:pearl.

I tried other materials, and the error still exists.

It seems working properly in singleplayer.

![image](https://github.com/Bawnorton/AllTheTrims/assets/32564494/d3290e7d-07a6-4ac8-a194-c6da9e88cc3e)

**Steps to Reproduce**
- Setup a dedicated server.
- Join the server.
- Trim the armour.
- You can see the %s Material error.

**What version of the mod are you using**
- All The Trims 3.4.2
- Minecraft 1.20.1
- Forge (Server side) 47.2.18

**Comment by Bawnorton** [comment]
Can't reproduce
