### ISSUE TITLE
Feature Request: EMI compatability cleanup

### ISSUE THREAD

**Issue by ImEnoan** [Benjamin-Norton/AllTheTrims#29]
When using EMI (and likely other recipe viewers) now every single item in the game has a listed 'use' of acting as a trim material. this is technically correct, but makes the uses list of every item needlessly bloated. 
EMI has options to hide certain items and/or recipes, hiding the smithing recipes would make this mod a lot less of a nuisance.

**Comment by Bawnorton** [comment]
EMI does not expose the api I need to make this viable.

I have already addressed this to the best I can but it's not solvable without significantly altering emi on my end (which is not great for compat)
https://github.com/Bawnorton/AllTheTrims/blob/arch-port/common/src/main/java/com/bawnorton/allthetrims/mixin/client/compat/emi/VanillaPluginMixin.java

I had raised this issue with emi but it was not added. Sorry
