### ISSUE TITLE
[Bug Report] REI cannot load alongside All The Trims

### ISSUE THREAD

**Issue by QwertRvg** [Benjamin-Norton/AllTheTrims#30]
**Expected Behaviour**
The game loads as intended

**Actual Behaviour**
When Forge completes loading, REI cannot load correctly.
![image](https://github.com/Bawnorton/AllTheTrims/assets/89683173/164a13b6-1630-41f2-9096-9bcd4550f59a)

**Steps to Reproduce**
- Download REI and All The Trims
- Load the game
- (not sure if other mods are also at fault)

**What version of the mod are you using**
3.4.2

**Helpful Files**
[rei-issues.log](https://github.com/user-attachments/files/15739158/rei-issues.log)
[rei.log](https://github.com/user-attachments/files/15739159/rei.log)

- latest.log
[latest.log](https://github.com/user-attachments/files/15739162/latest.log)

**Comment by syntheer** [comment]
The same bug occurs with the Fabric version - seems like it has some issue with the mixin (dontRegisterSmithingTrimRecipeDisplay)

**Comment by Bawnorton** [comment]
fixed in 3.4.3
