### ISSUE TITLE
Compatibility with other mod armors

### ISSUE THREAD

**Issue by froliko007** [Benjamin-Norton/AllTheTrims#31]
Does not work properly with armor pieces from ice and fire, alex mobs or deeper and darker.

![Captura de pantalla 2024-07-21 225800](https://github.com/user-attachments/assets/94383995-44aa-4bf6-9057-ecc3f2a769f4)

![Captura de pantalla 2024-07-21 225406](https://github.com/user-attachments/assets/e1e5a730-e96e-42e5-bb1c-cc851d0b2d4d)

It changes when i wear specific armors or change the camera: 

Warden armor set (deeper and darker:
![Captura de pantalla 2024-07-21 230607](https://github.com/user-attachments/assets/3644e134-2b72-4181-bd7a-5308665f463e)
![Captura de pantalla 2024-07-21 230644](https://github.com/user-attachments/assets/6b2f7d7a-50e3-4aee-ada4-387f5842d37e)

ice and fire (sheep set): 
![image](https://github.com/user-attachments/assets/3d59cd80-e696-4d91-9f19-725409817d89)

Please fix the scale set and the dragon steel sets. 

Black dragon scales set (silence trim, emerald material):
![Captura de pantalla 2024-07-21 231330](https://github.com/user-attachments/assets/afc67e2c-7b22-49ce-ae77-6a97211b1963)

Dragonsteel set (same trim and material)
![image](https://github.com/user-attachments/assets/ad09be59-f0b4-41d7-8153-290e71fcd3b2)

**Comment by Bawnorton** [comment]
Versions before 1.21 are no longer being maintained due to the 1.20.5 nbt changes basically requiring 2 completely different versions of this mod.
