### ISSUE TITLE
High memory and CPU usage

### ISSUE THREAD

**Issue by zc1108aaa** [Benjamin-Norton/AllTheTrims#35]
![H4$EVYR9XK7NGO19YU3G)HD](https://github.com/user-attachments/assets/1b312f86-60a7-4453-bbb3-60401a59d84d)
0
![39ST(UJ103WMQJC66 {~PNI](https://github.com/user-attachments/assets/29eb6ddc-d173-4c4b-81ba-c91addc18db5)
Only add 400, full
Do not add to restore normal operation
![ARN2O8_{A9~)WY13W9H%UNC](https://github.com/user-attachments/assets/7ec35c4c-5f5f-43b9-9d93-c132d05072ed)
[latest0.log](https://github.com/user-attachments/files/16739032/latest0.log)

1 small mod,
Compared to 100 large mods
100 times lag

**Comment by Bawnorton** [comment]
Use a profiler like spark to properly view cpu and memory usage from mc

**Comment by zc1108aaa** [comment]
Not added
![7CJCS NVX6 OL@H(CKU%)S](https://github.com/user-attachments/assets/5a72ed71-dead-48bd-9c94-9a86d931feaa)
add to
![EPJA~N09CE(48SS`@@KWV5J](https://github.com/user-attachments/assets/0d611ac8-0b9d-426d-b416-bdfe4b32f58f)
No response in a few minutes
I also deleted these mods
![image](https://github.com/user-attachments/assets/0f7be6ad-a39d-4003-9808-8d93086838b1)

**Comment by Bawnorton** [comment]
can you send the spark report created by running:
`/spark profiler start --timeout 30`

**Comment by zc1108aaa** [comment]
Not added![image](https://github.com/user-attachments/assets/569ce1da-04ce-4d2a-816e-9f4cdd434786)

**Comment by Bawnorton** [comment]
the link, not a screenshot

**Comment by zc1108aaa** [comment]
![aa1f8f8c1943e8c21da0ac6fe4345cec_0c294638f64eda1192d39021059d0e7b_auth_key=1724700951-7447888212-1532056735-6ae64785a5819651c2078d8cb9fe13a5](https://github.com/user-attachments/assets/07c8f40d-dd66-4c8e-9ad0-a637a2ceb765)

**Comment by zc1108aaa** [comment]
https://spark.lucko.me/LJJIyDVEmV

**Comment by Bawnorton** [comment]
> ![aa1f8f8c1943e8c21da0ac6fe4345cec_0c294638f64eda1192d39021059d0e7b_auth_key=1724700951-7447888212-1532056735-6ae64785a5819651c2078d8cb9fe13a5](https://private-user-images.githubusercontent.com/155424398/361507584-07c8f40d-dd66-4c8e-9ad0-a637a2ceb765.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTA3NjMsIm5iZiI6MTcyNDY5MDQ2MywicGF0aCI6Ii8xNTU0MjQzOTgvMzYxNTA3NTg0LTA3YzhmNDBkLWRkNjYtNGM4ZS05YWQwLWE2MzdhMmNlYjc2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxNjQxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTgzYTg2YjFmNmZiYzc2M2QyZjc3YTc3Zjk1Njg5ODA5NTQzZWE2NTUxODkyOGFmMmZiNjVhYjc4MjE3Mzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SKrnr2SdVN-lfFZSlRUQpkS6lZVZUcy6ERoMZIoTbnE)

can you send this file

**Comment by zc1108aaa** [comment]
![image](https://github.com/user-attachments/assets/6a626b25-08d5-4304-90c5-825ddb944499)

**Comment by Bawnorton** [comment]
ok, go to https://spark.lucko.me and upload the report, then share the link

**Comment by zc1108aaa** [comment]
increase
https://spark.lucko.me/jqCXp0Ty7l

**Comment by Bawnorton** [comment]
Had a look through, nothing indicates all the trims as the cause, notably it's not even recorded as impacting performance at all. Your main culprits are villager pathfinding, that's taking up a large amount of resources and slow memory reading, which I am going to assume is a result of you assigning `100000m` to the process. Assigning an excessive amount of memory to a process means that when the garbage collector triggers it has to clean up a lot of memory. Your gc is triggering every 10s and taking 3.1s to clear, that's 3.1s where nothing can happen so you're gonna get bad lag spikes.

Not enough memory: Garbage collector triggers too often => stuttering
Too much memory: Garbage collector triggers rarely but takes a few seconds to clear => large lag spikes

also look into optimised gc jvm args
