### ISSUE TITLE
[Bug] [1.20.1] [Forge] All ingredients and outputs are empty in the latest JEI

### ISSUE THREAD

**Issue by Tidy-Bear** [Benjamin-Norton/AllTheTrims#37]
# Description
All ingredients and outputs are empty in the latest JEI:
![image](https://github.com/user-attachments/assets/304d6483-147f-40c4-8c28-065267c11405)

# Step to Reproduction
1. Join a world.
2. Press 'U' over Smithing Table to show JEI's usages screen.
3. Select 'Armour Trimming' category.

# Environments
Minecraft 1.20.1
Forge 47.3.7
Architectury 9.2.14
All The Trims 3.4.3
JEI 15.16.2.73

# Logs
No warn or error.

**Comment by Bawnorton** [comment]
1.20.1 is no longer maintained. ATT has support for EMI/JEI and REI. Try another recipe browser
