### ISSUE TITLE
Mod makes my modpack unplayable

### ISSUE THREAD

**Issue by Verocter25** [Benjamin-Norton/AllTheTrims#38]
Every time the mod is enabled on my modpack it makes it so the game slows down to about one frame per minute.
Is there a way to prevent this?

I can share the modpack if needed

**Comment by Bawnorton** [comment]
use spark to run a client profile and send that here https://www.curseforge.com/minecraft/mc-mods/spark

**Comment by Verocter25** [comment]
how do i get that? (not the mod) Do i have to get that from files or would I have to type a command to get it?

**Comment by Bawnorton** [comment]
https://spark.lucko.me/docs/Command-Usage use `/sparkc` instead of `/spark`

**Comment by Verocter25** [comment]
I don't believe its possible to
Because everything gets slowed. Minecraft basically stops after 10 seconds, and my computer remains really slow

**Comment by Bawnorton** [comment]
If you have a recipe browser mod can you try removing that temporarily

**Comment by Verocter25** [comment]
https://spark.lucko.me/3UuQ4ZAqOw
Its a lot better now but I may need that recipe browser for the modpack

**Comment by Bawnorton** [comment]
I know what the bug is, it's related to REI and memory usage calculating the smithing recipes. Try updating REI to the latest version (I haven't tested this so I may need to update ATT) or use a different recipe browser.

**Comment by Bawnorton** [comment]
Close if resolved

**Comment by Verocter25** [comment]
Alr yeah seemed to solve it by switching to JEI
Thanks 👍
