### ISSUE TITLE
Putting a trim on modded armor crashes the game

### ISSUE THREAD

**Issue by Verocter25** [Benjamin-Norton/AllTheTrims#39]
New issue: when i try putting a trim on modded armor in the smithing table it crashes the game.
From what I can tell its maybe from rendering it.
It occurs immediately after putting the trim in the table

Crash report:
https://mclo.gs/65phSVa

Doesn't seem to affect only a specific mod's armor

**Comment by Bawnorton** [comment]
You have many different mods all interacting with the armour rendering code from different loaders, att is not responsible for this crash.

Try removing these mods in order until it doesn't crash:
`stacked_trims`
`cosmetic-armor`
`player_animator`
`armoroftheages`
`alexcaves`
`quark`
`essential`
`create`

**Comment by Verocter25** [comment]
Ah Alr I'll have to check later
Thanks for helping out with my issues btw sorry if any of them were dumb questions lol
