### ISSUE TITLE
[Bug Report] Armour from [Unknown Mod] is incompatible with AllTheTrims

### ISSUE THREAD

**Issue by zachsai** [Benjamin-Norton/AllTheTrims#4]
![image](https://github.com/Benjamin-Norton/AllTheTrims/assets/63996164/2ce0ade4-5c48-4a7d-8249-9ac61be812b1)

**Comment by Bawnorton** [comment]
Thanks for reporting, I'll look into it.

**Comment by Bawnorton** [comment]
The issue is not with rats but with the armour mod. Which mod is that chestplate from?

<img width="342" alt="Screenshot 2023-07-08 at 3 53 31 PM" src="https://github.com/Benjamin-Norton/AllTheTrims/assets/18416784/ad5381c1-c358-4a15-8299-e77e5fcbcd8e">

**Comment by zachsai** [comment]
it was from alexsmobs, but i also tested with a gold chestplate with a resourcepack

**Comment by Bawnorton** [comment]
I can't reproduce this. What is the exact mod and texture pack you are using for that chestplate which has a missing texture? All of alex's mobs armour work. 
<img width="342" alt="Screenshot 2023-07-09 at 12 09 34 PM" src="https://github.com/Benjamin-Norton/AllTheTrims/assets/18416784/addf5791-7a8d-4b01-9215-1cb967bf5916">

**Comment by zachsai** [comment]
https://www.curseforge.com/minecraft/texture-packs/nekos-enhanced-tools-and-armor/comments

**Comment by Bawnorton** [comment]
This works as expected
<img width="368" alt="Screenshot 2023-07-09 at 1 18 52 PM" src="https://github.com/Benjamin-Norton/AllTheTrims/assets/18416784/237b6200-1401-40b0-8ad3-5e8f4431d53b">

**Comment by Bawnorton** [comment]
please can you provide your `latest.log`
