### ISSUE TITLE
Crash when applying non-vanilla trim to elytra (Elytra Trim compatibility)

### ISSUE THREAD

**Issue by Gardecune** [Benjamin-Norton/AllTheTrims#43]
The game crashed whilst rendering entity in world
Error: java.lang.NoSuchMethodError: 'void com.bawnorton.allthetrims.client.shader.TrimShaderManager.setContext(net.minecraft.class_1297, net.minecraft.class_1792)'

**Comment by Bawnorton** [comment]
Should be fixed in the next elytra trims update
