### ISSUE TITLE
[Rendering Bug] Toggle "Override Existing Trim" Will Cause Texture Rendering Bug

### ISSUE THREAD

**Issue by XEpicLi** [Benjamin-Norton/AllTheTrims#44]
No config changed: Get an armor with trim. Should see trim texture, and work properly on players, armor stand and mobs.
![2024-10-06_14 17 50](https://github.com/user-attachments/assets/385bba03-e7f7-4a5a-8079-e76c3ecd4b3f)
![2024-10-06_14 18 10](https://github.com/user-attachments/assets/92b188e7-0f8d-481a-9f43-34ade2c185a2)

Toggle "Override Existing Trim": No trim texture on armor in inventory. Armor texture seemed to be missing on players, armor stand and mobs.
![2024-10-06_14 16 32](https://github.com/user-attachments/assets/03981b47-2765-4113-ae13-36b4a891e429)
![2024-10-06_14 16 57](https://github.com/user-attachments/assets/d0588c7d-33f0-4162-a80a-f7cb48adacc0)
![2024-10-06_14 17 19](https://github.com/user-attachments/assets/58c94bfb-7060-464d-bb63-4dea9bf52f93)
![2024-10-06_14 17 31](https://github.com/user-attachments/assets/9cff7e1b-09b9-412c-84ea-6308795ae504)

**Comment by XEpicLi** [comment]
Version: 1.21 Fabric. All using mods are below.
![image](https://github.com/user-attachments/assets/f07baceb-bd75-46e7-8faf-d506251e2e73)

**Comment by Bawnorton** [comment]
Fixed in 4.0.8

**Comment by XEpicLi** [comment]
so fast
