### ISSUE TITLE
[Suggestion]Shift + Left Click Should Move Trim Templates into Trim Slot, Not Material.

### ISSUE THREAD

**Issue by XEpicLi** [Benjamin-Norton/AllTheTrims#45]
Just like title, Shift + left click will move items into Smithing Table. However, with this mod, if you hold Shift and left click trim templates, templates will be moved into material slot, not template slot(expected).
And what's more, only Sentry trim template will be moved correctly. All other templates will be considered "material".

**Comment by XEpicLi** [comment]
Just like another issue I sent minutes ago, 1.21 Fabric with these mods.
![image](https://github.com/user-attachments/assets/5aea08a4-3a1a-4f34-8224-ee4eeee1d0f9)

**Comment by Bawnorton** [comment]
Unfortunately this bug can't be fixed without disabling trim templates as materials or completely replacing the recipe matcher. I looked into this and in order to fix it I have to break recipe browsers which is a non-option
