### ISSUE TITLE
crash with latest allthetrims version (neoforge 1.21.1)

### ISSUE THREAD

**Issue by VaporeonScripts** [Benjamin-Norton/AllTheTrims#48]
https://mclo.gs/UIGk8VM

**Comment by Bawnorton** [comment]
missing [runtimetrims](https://www.curseforge.com/minecraft/mc-mods/runtimetrims)

**Comment by VaporeonScripts** [comment]
why is it not listed as needed :sob:

**Comment by Bawnorton** [comment]
the dep should be listed on cf/mr

**Comment by VaporeonScripts** [comment]
https://mclo.gs/GE5lSCL still crashes

**Comment by Bawnorton** [comment]
Sigh, looks like neoforge itself has made changes since 1.21 and thus requires a 1.21.1 version despite the mc code being identical

**Comment by VaporeonScripts** [comment]
well, prob some changes causes that, btw 
![image](https://github.com/user-attachments/assets/7d527f5a-21c5-4893-8dd1-217abbdfbe3b)

**Comment by Bawnorton** [comment]
[RuntimeTrims-1.0.2-neoforge+1.21.1.jar.zip](https://github.com/user-attachments/files/17451508/RuntimeTrims-1.0.2-neoforge%2B1.21.1.jar.zip)

Try this build

**Comment by Bawnorton** [comment]
Deps fixed in 5.0.1 and crash fixed in RT 1.0.2 for neo 1.21.1, both published on mr/cf

**Comment by VaporeonScripts** [comment]
what if mc still crashes lol https://mclo.gs/UAgNWcL

**Comment by Bawnorton** [comment]
Huh, literally just tested neo 21.1.72 w/ latest RT and ATT and it doesn't crash.. which means its likely a conflict .. *dies*

**Comment by VaporeonScripts** [comment]
bruh, what do i do then

**Comment by Bawnorton** [comment]
>  [✔] RuntimeTrims-1.0.2-neoforge 1.21

you downloaded the wrong one, need RuntimeTrims-1.0.2-neoforge **1.21.1**

**Comment by VaporeonScripts** [comment]
well, u didnt upload 1.21.1 (i mean i only see 1.21)

**Comment by VaporeonScripts** [comment]
wait,it shows now

**Comment by VaporeonScripts** [comment]
seems to work now
