### ISSUE TITLE
GregTech materials turns grey

### ISSUE THREAD

**Issue by MineTimoff** [Benjamin-Norton/AllTheTrims#51]
When using GregTech materials for trims, they're becoming grey
![image](https://github.com/user-attachments/assets/db3945c2-b8bf-449d-80ad-ae855b326a5a)
maybe it's because of gregtech textures doesn't have color initially

**Comment by Bawnorton** [comment]
What version of ATT?

**Comment by MineTimoff** [comment]
> What version of ATT?

3.4.3

**Comment by Bawnorton** [comment]
Yeah that version doesn't support colour provider coloured items

**Comment by MineTimoff** [comment]
but it's the latest version for minecraft 1.20.1...

**Comment by Bawnorton** [comment]
Yes, 1.20.1 was dropped when 1.21 was released due to the number of significant internal changes
