### ISSUE TITLE
Issue with compatibility with optifine

### ISSUE THREAD

**Issue by Varivitax** [Benjamin-Norton/AllTheTrims#57]
Im running a small custom pack rn, and i disabled all the mods till i found out it _**_wasn't compatible with optifine_**_. Is that a problem on my side or is the pack just not compatible, Btw im runnin it through curse forge. It crashes before it launches, giving an error code -1. I need optifine to run the shaders and resource packs, but if it cant be compatible i can change to iris i guess. Running version 1.20.1 the most recent one

**Comment by Bawnorton** [comment]
Don’t use optifine in modern MC. Much better alternatives exist https://optifine.alternatives.lambdaurora.dev/
