### ISSUE TITLE
Bug with Optifabric v1.13.25+1.20.1

### ISSUE THREAD

**Issue by bvhfve** [Benjamin-Norton/AllTheTrims#7]
![image](https://github.com/Benjamin-Norton/AllTheTrims/assets/95630070/e014920f-fbc1-4a52-b4ee-8d4f746e879b)

I'm having this weird texture bug when using your mod with Optifabric and Optifine.

![image](https://github.com/Benjamin-Norton/AllTheTrims/assets/95630070/9308ab50-1c94-4a64-94d2-bfc329ddea5f)
Tested with these mods only.
-------------------------------------------------------------------------------------------------------------------------------------------
[Older log](https://pastebin.com/gTHacmvn)

[latest.log](https://github.com/Benjamin-Norton/AllTheTrims/files/12063271/latest.log)

**Comment by Bawnorton** [comment]
Optifine will not be supported. Please see this page for why and what alternatives you can use.

https://lambdaurora.dev/optifine_alternatives/

**Comment by bvhfve** [comment]
:(( I didn't know that. Also I really don't want to use Optifine and Optifabric at all since it broke tons of mods but my potato laptop can't seem to give as much fps with Sodium as using Optifine. Are there any other solutions ?

**Comment by Bawnorton** [comment]
Install the fabulously optimised modpack: https://www.curseforge.com/minecraft/modpacks/fabulously-optimized
And try playing with that.

**Comment by bvhfve** [comment]
I also tried that but sadly no luck :( anyway thanks for replying so fast

**Comment by Bawnorton** [comment]
Double check you've got updated drivers but if you can't even get it to run with FO, you'll need to get a better PC. Or, albeit requiring some technical knowledge, setup a server on oracle (free) and connect to the server to play. That will offload a lot of the processing to the server and may allow your game to run better as your PC doesn't have to do all the server side calculations which are quite intensive.
