### ISSUE TITLE
Texture bug with Sodium

### ISSUE THREAD

**Issue by bvhfve** [Benjamin-Norton/AllTheTrims#8]
Yep it's me again :) it seems that the weird texture bug I mentioned earlier doesn't only occur with Optifine. 
Mod(pack) installed: Fabulously Optimized + some minor mods (the bug persist even after removing those)
[latest.log](https://github.com/Benjamin-Norton/AllTheTrims/files/12063326/latest.log)

**Comment by Bawnorton** [comment]
Well that's odd, your file system doesn't allow file names to contain ":", which I've not seen before. I can patch this tomorrow but you can fix this now by opening the all the trims config file and setting debug to false.
